"""initial schema (all Bauauftrag entities) + immutability triggers

Decimal columns are TEXT (exact), timestamps are ISO-8601 UTC TEXT.

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 (UTC+2 local build time)

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

IMMUTABLE_TABLES = ("products", "offer_snapshots", "evidence", "rule_versions", "quotes",
                    "route_evaluations", "execution_results")


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chain', sa.String(length=60), nullable=False),
    sa.Column('contract_address', sa.String(length=200), nullable=False),
    sa.Column('decimals', sa.String(length=10), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'contract_address', name='uq_asset_chain_contract')
    )
    op.create_table('operator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('max_budget_eur', sa.String(length=64), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_key', sa.String(length=500), nullable=False),
    sa.Column('face_value', sa.String(length=64), nullable=False),
    sa.Column('face_currency', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('variant', sa.String(length=200), nullable=False),
    sa.Column('seller', sa.String(length=200), nullable=False),
    sa.Column('redemption_program', sa.String(length=200), nullable=False),
    sa.Column('product_family', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('sources_ok', sa.Text(), nullable=False),
    sa.Column('sources_failed', sa.Text(), nullable=False),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('evaluations_created', sa.Integer(), nullable=False),
    sa.Column('alerts_enqueued', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('last_success_at', sa.String(length=40), nullable=True),
    sa.Column('last_error_at', sa.String(length=40), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('subject_ref', sa.String(length=100), nullable=False),
    sa.Column('captured_at', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_subject_ref'), ['subject_ref'], unique=False)

    op.create_table('offer_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('route_key', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.String(length=40), nullable=False),
    sa.Column('price_amount', sa.String(length=64), nullable=False),
    sa.Column('price_currency', sa.String(length=10), nullable=False),
    sa.Column('price_text_raw', sa.String(length=200), nullable=False),
    sa.Column('price_includes_fees', sa.Boolean(), nullable=False),
    sa.Column('fees', sa.Text(), nullable=False),
    sa.Column('advertised_quantity', sa.String(length=20), nullable=False),
    sa.Column('advertised_quantity_at', sa.String(length=40), nullable=False),
    sa.Column('advertised_quantity_scope', sa.String(length=60), nullable=False),
    sa.Column('checkout_confirmed_quantity', sa.String(length=20), nullable=False),
    sa.Column('checkout_confirmed_quantity_at', sa.String(length=40), nullable=False),
    sa.Column('checkout_confirmed_quantity_scope', sa.String(length=60), nullable=False),
    sa.Column('purchased_quantity', sa.String(length=20), nullable=False),
    sa.Column('purchased_quantity_at', sa.String(length=40), nullable=False),
    sa.Column('purchased_quantity_scope', sa.String(length=60), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['offer_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offer_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_snapshots_route_key'), ['route_key'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('route_key', sa.String(length=200), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('depth_quantity', sa.String(length=20), nullable=False),
    sa.Column('fees', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.String(length=40), nullable=False),
    sa.Column('valid_until', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_route_key'), ['route_key'], unique=False)

    op.create_table('route_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_key', sa.String(length=200), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('operator_profile_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discount', sa.String(length=64), nullable=False),
    sa.Column('profit_eur', sa.String(length=64), nullable=False),
    sa.Column('edge', sa.String(length=64), nullable=False),
    sa.Column('evaluated_quantity', sa.String(length=20), nullable=False),
    sa.Column('inputs', sa.Text(), nullable=False),
    sa.Column('outputs', sa.Text(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_profile_id'], ['operator_profiles.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_evaluations_route_key'), ['route_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_evaluations_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('route_key', sa.String(length=200), nullable=False),
    sa.Column('route_evaluation_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('sink', sa.String(length=40), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.String(length=40), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.String(length=40), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['route_evaluation_id'], ['route_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_route_key'), ['route_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_state'), ['state'], unique=False)

    op.create_table('execution_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchased_quantity', sa.String(length=20), nullable=False),
    sa.Column('purchased_quantity_scope', sa.String(length=60), nullable=False),
    sa.Column('total_cost_eur', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['route_evaluation_id'], ['route_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    for t in IMMUTABLE_TABLES:
        op.execute(f"CREATE TRIGGER {t}_no_update BEFORE UPDATE ON {t} "
                   f"BEGIN SELECT RAISE(ABORT, 'immutable table {t}: create a new version'); END;")
        op.execute(f"CREATE TRIGGER {t}_no_delete BEFORE DELETE ON {t} "
                   f"BEGIN SELECT RAISE(ABORT, 'immutable table {t}: delete not allowed'); END;")


def downgrade() -> None:
    """Downgrade schema."""
    for t in IMMUTABLE_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {t}_no_update")
        op.execute(f"DROP TRIGGER IF EXISTS {t}_no_delete")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_results')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_state'))
        batch_op.drop_index(batch_op.f('ix_alerts_route_key'))

    op.drop_table('alerts')
    with op.batch_alter_table('route_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_evaluations_status'))
        batch_op.drop_index(batch_op.f('ix_route_evaluations_route_key'))

    op.drop_table('route_evaluations')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_route_key'))

    op.drop_table('quotes')
    with op.batch_alter_table('offer_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_snapshots_route_key'))

    op.drop_table('offer_snapshots')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_subject_ref'))

    op.drop_table('evidence')
    op.drop_table('sources')
    op.drop_table('scan_runs')
    op.drop_table('rule_versions')
    op.drop_table('products')
    op.drop_table('operator_profiles')
    op.drop_table('assets')
    # ### end Alembic commands ###
