"""Model-judgment ENRICHMENT and SAFETY layer (TypeSafe System One / Jev), docs/decisions.md D-42.

Hard rules (enforced by code + tests in tests/test_judgments.py):
- Judgments are inferred HINTS. They never enter the deterministic Decimal valuation math
  (`valuation/` stays authoritative and untouched) and never enqueue/trigger an alert.
- Nothing here purchases, checks out, redeems, transfers, logs in or bypasses anything
  (no CAPTCHA/bot-protection/region/KYC workaround, no user-agent spoofing). Safety signals can only
  BLOCK/deprioritize, never unlock.
- Numbers are never generated by the model: "select, don't generate" (code extracts Decimal candidates,
  the model picks an option key, code copies the already-extracted Decimal).
- OFF by default; the default provider is the no-network NullJudgmentProvider. No network at import time.
"""

from .base import (ABSTAIN_SIGNAL, JudgmentKind, JudgmentProvider, JudgmentRequest, JudgmentResult, Question,
                   abstain_all)
from .null_provider import NullJudgmentProvider

__all__ = ["ABSTAIN_SIGNAL", "JudgmentKind", "JudgmentProvider", "JudgmentRequest", "JudgmentResult", "Question",
           "abstain_all", "NullJudgmentProvider"]
